name: deploy_clasp_library

env:
  CLASP_FILE: .clasprc.json
  CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  pre_build:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3

      - name: create_clasp_credentails
        if: ${{ env.CLASP_CREDENTIALS != '' }}
        run: |
          echo $CLASP_CREDENTIALS >> "$CLASP_FILE"

      - name: exists_clasp_file
        run: |
          if [ -f "$FILE" ]; then exit 1; fi

  build:
    needs: pre_build
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: test
        run: |
          ls -la
