name: deploy_clasp_library

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  pre_build:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3

      - name: create_clasp_credentails
        env:
          CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
        if: ${{ env.CLASP_CREDENTIALS != "" }
        run: |
          echo $CLASP_CREDENTIALS >> .clasprc.json
