name: deploy_clasp_library

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
env:
  clasp_credentials: ${{ vars.CLASP_CREDENTIALS }}

jobs:
  pre_build:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
      - name: log_creds
        run: |
          echo "This is the src: $CLASP_CREDENTIALS"
