name: deploy_clasp_library

env:
  CLASP_FILE: .clasprc.json
  CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
  ARTIFACTS_NAME: clasp-ci-${{ github.event.repository.id }}
  NODE_VERSION: 16

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  pre_build:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: create_clasp_credentails
        if: ${{ env.CLASP_CREDENTIALS != '' }}
        run: |
          echo $CLASP_CREDENTIALS >> "$CLASP_FILE"

      - name: exists_clasp_file
        run: |
          if [ -f "$FILE" ]; then exit 1; fi

      - name: save_pre_build_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          path: .

  build:
    needs: pre_build
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v3

      - name: yarn_cache_dir_path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: download_artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          path: .

      - name: install_dependencies
        run: |
          yarn install --frozen-lockfile

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: save_pre_build_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v3

      - name: download_artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          path: .

      - name: clasp_login
        run: |
          yarn clasp:login
